services:
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    container_name: dragonfly
    command: ['--requirepass', 'your_password', '--cluster_mode=emulated', '--lock_on_hashtags']
    ulimits:
      memlock: -1
    ports:
      - '6379:6379'
    volumes:
      - dragonfly-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_database
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-ppassword',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  dragonfly-data:
  mysql-data:
